
export const restaurants = [
   {
      name: "Syv Ni 13",
      reviews: 63,
      location: "aarhus",
      desc: "Europæisk, Fusion, Skandinavisk.",
      info: "På Syv Ni 13 laver vi SOCIAL DINING. Det betyder små serveringer, som kan deles af hele bordet. Udgangspunktet er det nordiske køkken og sæsonens råvarer. Inspirationen kommer fra hele verdenen. Stilen er minimalistisk. Det kommer både til udtryk i vores mad, men også vores indretning, såvel som vin- og cocktailkortet.",
      locationref: "http://maps.apple.com/?daddr=Syv+Ni+13&dirflg=d&t=h",
      image:"https://media-cdn.tripadvisor.com/media/photo-s/1a/dc/6e/a2/social-dining.jpg",
      slug:"syv-ni-13",
      address:"Frederiksgade 74, 8000 Aarhus",
      openinghours: {
         monday: "17-00",
         tuesday: "17-00",
         wednesday: "17-00",
         thursday:"17-00",
         friday:"17-00",
         saturday:"10-14 & 17-00",
         sunday:"Lukket"
      },
      id: "1"
   },
   {
      name: "Keyser Social",
      review: 63,
      location: "aarhus",
      desc:"Asiatisk",
      info:"Hos Keyser Social arbejder vi allerhelst udenom normer og forventninger. Med afsæt i Fjernøsten og referencer til det nordiske køkken gør vi en dyd ud af at servere mad, der er en fryd for både øjne og smagsløg.",
      locationref: "http://maps.apple.com/?daddr=Keyser+Socia l+Aarhus&dirflg=d&t=h",
      image:"https://sua.dinnerbooking.eu/img/restaurants/2986/530x250/1631270589_741-2986-keyser-social-aarhus.jpg",
      slug:"keyser-social",
      address:"Frue Kirkeplads 4, 8000 Aarhus",
      openinghours: {
         monday: "17-21",
         tuesday: "17-21",
         wednesday: "17-21",
         thursday:"17-22",
         friday:"17-22",
         saturday:"17-22",
         sunday:"17-21"
      },
      id: "2",
   },
   {
      name: "Restaurant Nögen",
      review: 4,
      location: "aarhus",
      desc:"Social Dining med fokus på at kokkerere madspild om til en unik smagsoplevelse, hvor ingen fremragende ingredienser går til spilde.",
      info:"Restaurant Nögen tilbyder et inspirerende nyt koncept, som bygger på unikke kreationer af overskydende varer. Vores ambition er, at få den gode tanke om at undgå madspild til, at gå hånd i hånd med den gode madoplevelse. Intentionen bag konceptet er minimalistiske, lækre og smagfulde madoplevelser, der bærer præg af sæsonens råvarer, og hvor der kræses om den enkelte ingrediens. Lad tiden stå stille for en aften og læn dig tilbage, mens du bliver ført på en rejse af unikke smagsoplevelser og god stemning.",
      locationref: "http://maps.apple.com/?daddr=Restaurant+Nögen,+Banegårdspladsen+4,+St.+th,+8000+Aarhus&dirflg=d&t=h",
      image:"https://usercontent.one/wp/www.restaurantnoegen.dk/wp-content/uploads/2022/03/IMG_0615-scaled.jpg?media=1644918691",
      slug:"restaurant-noegen",
      address:"Banegårdspladsen 4, St. th, 8000 Aarhus",
      openinghours: {
         monday: "Lukket",
         tuesday: "11:30-23",
         wednesday: "11:30-23",
         thursday:"11:30-23",
         friday:"11:30-02",
         saturday:"11:30-02",
         sunday:"Lukket"
      },
      id: "3"
   },
   {
      name: "Restaurant Olive",
      review: 15,
      location: "aalborg",
      desc:"Restaurant Olive har nu i 13 år serveret lækkert mad fra hjertet.",
      info:"Restaurant Olive har nu i 13 år serveret lækkert mad fra hjertet. Høj kvalitet til en fornuftig pris har givet stor tilfredshed hos vore mange gæster. Som en af de første restauranter i Aarhus arbejder vi efter konceptet, at du som gæst må medbringe dine egne udvalgte vine. Ved valg af menu tager vi udgangspunkt i de råvarer der er på markedet. Som dog oftest bestemt af årstiden og den optimale kvalitet af råvarerne. Vi tilstræber at lave en menu, der er inspireret af det danske- og sydeuropæiske køkken. Vores nuværende menu samt priser finder du på vores væg. Har du behov for et lokale til en lukket fest, konfirmation, bryllup, fødselsdag eller lignende, er Olive en nærliggende mulighed. Vi har lokalerne hvor vort personale står fuldt ud til din rådighed, og vi serverer - helt efter aftale med dig - en passende menu",
      locationref:"http://maps.apple.com/?daddr=Restaurant+Olive,+Kaløgade,+Aarhus&dirflg=d&t=h",
      image:"https://olive.dk/wp-content/uploads/2020/08/CED2D835-D811-48CA-961B-9616AD8DE0C7-scaled.jpg",
      slug:"restaurant-olive",
      address:"Kaløgade 1, 8000 Aarhus",
      openinghours: {
         monday: "17:30-22",
         tuesday: "17:30-22",
         wednesday: "17:30-22",
         thursday:"17:30-22",
         friday:"17:30-23",
         saturday:"17:30-23",
         sunday:"Lukket"
      },
      id: "4"
   },
   {
      name:"Cafe Piaf",
      review: 9,
      location:"aarhus",
      desc:"Hyggelig fransk brasserie, hvor vi virkelig kæler om maden og ikke mindst vore gæster.",
      info:" Piaf er en ægte kvarterrestaurant i Paris, men vi er på jægergårdsgade i Aarhus. Vi plejer også ægte pleje af maden ligesom i Frankrig. Vi tager råmaterialerne fra flere steder . Men uanset hvor vores råvarer kommer fra, er det altid smagen, der kommer først. Man kan sige, at vi har en fransk måde at lave mad på. Der er altid nogle franske klassikere som snegle, chèvre chaud, boeuf bourguignon. Men menuen kan også omfatte aborre med rogn, rødder, kanin … Vi har en ny menu efter hver  sæson, men det grundlæggende og vores tankegang er altid genkendelige. Naturligvis er drikke tæt på vores hjerter, ligesom det ofte er i Frankrig. Vi har altid nogle favoritter, der altid er i flasker og glas, vi lader ofte spændende vin komme på besøg, og nogle gange kan vi vælge noget magisk ud af at skjule.",
      locationref:"http://maps.apple.com/?daddr=Piaf,+Jægergårdsgade,+Aarhus&dirflg=d&t=h",
      image:"https://www.cafepiaf.dk/wp-content/uploads/2022/03/Piaf1.jpg",
      slug:"cafe-piaf",
      address:"Jægergårdsgade 40, 8000 Aarhus",
      openinghours: {
         monday: "12-22",
         tuesday: "12-22",
         wednesday: "12-22",
         thursday:"12-23:30",
         friday:"12-23:30",
         saturday:"11-23",
         sunday:"Lukket"
      },
      id: "5"
   },
   {
      name:"Løve's Bog- og Vincafe",
      review: 2,
      location:"aarhus",
      desc:"Bogcafé, vincafé, antikvariat og forlag",
      info:"Historien bag Løve's Bogcafé går tilbage til en kold vinterdag i Aarhus i slutningen af 2004, hvor idéen om en bogcafé for første gang dukkede op i hovedet på grundlæggeren. Eller det vil sige, den helt rigtige historie går faktisk endnu længere tilbage, mere præcist til Svendborg i slutningen af firserne, hvor bogen Brødrene Løvehjerte for første gang blev læst op for to lyttende drenge, hvoraf den ene tyve år senere fik muligheden for at føre sin drøm ud i virkeligheden. En drøm, der blev formet af en lille, blond drengs skikkelse, som var et billede skabt af en svensk forfatterindes fantastiske fantasi. Et billede på en løves mod og et hjertes kærlighed. Drengen hed Jonatan Løve, og i hans billede er Løve's Bogcafé skabt.",
      locationref:`http://maps.apple.com/?daddr=Løve's+Bog-+og+Vincafé,+Nørregade,+Aarhus&dirflg=d&t=h`,
      image:"https://media-cdn.tripadvisor.com/media/photo-s/18/b8/aa/16/love-s-bog-og-vincafe.jpg",
      slug:"loves-bog-og-vincafe",
      address:"Nørregade 32, 8000 Aarhus",
      openinghours: {
         monday: "09-22",
         tuesday: "09-22",
         wednesday: "09-22",
         thursday:"09-00",
         friday:"09-00",
         saturday:"10-00",
         sunday:"10-18"
      },
      id: "6"
   },
   {
      name:"Restaurant Mellemrum",
      review: 25,
      location:"aarhus",
      desc:"Restaurant MellemRum - håndværk, hygge og energi!",
      info:"God restaurant i Århus C med lækker mad til gode priser. Køkkenet har bund i god dansk mad med inspiration i det Franske men også Italienske og internationale madstile er repræsenteret. Godt vinkort med meget fornuftige priser. Vinmenu til Menu MellemRum til fair pris. Afslappet betjening med en super god stemning.",
      locationref: "http://maps.apple.com/?daddr=Restaurant+MellemRum,+Fredens+Torv,+Aarhus&dirflg=d&t=h",
      image:"https://scontent-cph2-1.xx.fbcdn.net/v/t39.30808-6/263434461_10159850911842812_3457983835068762075_n.jpg?_nc_cat=108&ccb=1-5&_nc_sid=0debeb&_nc_ohc=I6f8Z5I8vL8AX9ZWn5S&_nc_ht=scontent-cph2-1.xx&oh=00_AT-xtkDKPPyHI_QJNtaoqmuiE9xs-my0jZR8uaTh-MfiGg&oe=62408B00",
      slug:"restaurant-mellemrum",
      address:"Fredens Torv 2, 8000 Aarhus",
      openinghours: {
         monday: "17-23",
         tuesday: "17-23",
         wednesday: "17-23",
         thursday:"17-23",
         friday:"17-23",
         saturday:"17-23",
         sunday:"Lukket"
      },
      id: "7"
   },
   {
      name:"Restaurant Ombord",
      review:24,
      location:"aarhus",
      desc:"SAMVÆR, HYGGE & GOD MAD I JÆGERGÅRDSGADE",
      info:"God mad i Århus - På Restaurant Ombord går vi op i god mad af gode råvarer! Vi serverer lækre retter af de bedste råvarer årstiden byder på - og laver byens bedste Bøf Bearnaise! Kom selv og prøv god mad i Århus!",
      locationref:"http://maps.apple.com/?daddr=Restaurant+Ombord,+Jægergårdsgade,+Aarhus&dirflg=d&t=h",
      image:"https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/e4/ac/ec/for-lokalet-med-den-karakteris.jpg?w=800&h=600&s=1",
      slug:"restaurant-ombord",
      address:"Jægergårdsgade 71, 8000 Aarhus",
      openinghours: {
         monday: "Lukket",
         tuesday: "17-23",
         wednesday: "17-23",
         thursday:"17-23",
         friday:"15-23",
         saturday:"10-23",
         sunday:"10-23"
      },
      id: "8"
   },
   {
      name:"Restaurant Komfur",
      review: 30,
      location:"aarhus",
      desc:"På Restaurant Komfur er der 3 væsentlige værdier, der præger alt, hvad vi gør: håndværk, hygge og energi",
      info:"På Restaurant Komfur er der 3 væsentlige værdier, der præger alt, hvad vi gør: håndværk, hygge og energi! Det er de værdier, der giver os lyst til at stå op om morgenen, giver os daglig motivation og udfordring, og som gør, at vores gæster får en god oplevelse, når de er sammen med os. Vores menukort er simpelt. Det består af 5 forretter, 5 hovedretter, oste og 2 desserter. Det skal ikke være kompliceret at gå på restaurant. Hvis man selv kan hælde vand op i sit glas derhjemme, kan man sikkert også, når man er hos os. Og forstå os ret – vi ved godt, der skal være forskel på ude og hjemme. Men det handler om god mad og vin – ikke om det stive puds og fastlåste forestillinger om, hvad god service er. Derfor må vores gæster hjælpe lidt til, så bruger vi i stedet tiden på at give jer oplevelser, I ikke får hjemme ved køkkenbordet. Tja vi gør faktisk bare det, vi er bedst til.",
      locationref:"http://maps.apple.com/?daddr=Restaurant+Komfur,+Guldsmedgade,+Aarhus&dirflg=d&t=h",
      image:"https://files.guidedanmark.org/files/484/208034_Ret-Restaurant-Komfur-1.jpg?width=987",
      slug:"restaurant-komfur",
      address:"Guldsmedgade 38, 8000 Aarhus",
      openinghours: {
         monday: "17-23",
         tuesday: "17-23",
         wednesday: "17-23",
         thursday:"17-23",
         friday:"17-23",
         saturday:"17-23",
         sunday:"17-23"
      },
      id: "9"
   },
   {
      name:"Bardok",
      review: 19,
      location:"aarhus",
      desc:"Mad, vin og sprut fra lande i og uden for den europæiske union",
      info:"Bardok betyder økse på ungarsk og noget a la uorden på russisk, hvis man staver det lidt anderledes. Vi laver mad fra Sicilen til Stepanakert. Altså en slags neo osmannisk bistro. Pasta lavet med vores hænder og en kirsebærpind. Lækker kartoffel booze lavet af gode mænd. Charcuterie lavet lige udenfor Skanderborg af os. Dumpling, pickles og høj fed tyrkisk rock. Og åbent til rimelig sent.",
      locationref:"http://maps.apple.com/?daddr=Bardok,+Åboulevarden,+Aarhus&dirflg=d&t=h",
      image:"https://spiseguidenaarhus.dk/wp-content/uploads/2021/09/Bardok-2-1024x768.jpg",
      slug:"bardok",
      address:"Åboulevarden 51, 8000 Aarhus",
      openinghours: {
         monday: "Lukket",
         tuesday: "17-22",
         wednesday: "17-22",
         thursday:"17-22",
         friday:"17-22",
         saturday:"17-22",
         sunday:"Lukket"
      },
      id: "10"
   },
   {
      name:"Tapastreat",
      review: 45,
      location:"koebenhavn",
      desc:"Vi laver lækre tapasløsninger til private kunder og virksomheder.",
      info:"Tapas Treat er traditionelle retter tilberedt af nytænkende hoveder og båret af personlige historier. Når du tager en bid, håber vi, dine tanker vandrer til de verdensdele, de er inspireret af. Og vi håber, at de kan skabe mindelsesværdige øjeblikke, ligesom de har gjort for os bag Tapas Treat – både den første gang, vi smagte retterne i forskellige kulturelle sammenhænge på forskellige rejser med forskellige mennesker, men også forskellige aftener i forskellige parker og dengang ved stranden, hvor solen gav hele himlen et magisk, rødligt skær og skabte en magisk stemning, og vi kunne blive ved.",
      locationref:"http://maps.apple.com/?daddr=Tapas+Treat,+Kastrupvej,+København+S&dirflg=d&t=h",
      image:"https://tapastreat.dk/wp-content/uploads/OM-TT-smag-og-dele-2.jpg",
      slug:"tapastreat",
      address:"Kastrupvej 110, 2300 København S",
      openinghours: {
         monday: "14-20",
         tuesday: "14-20",
         wednesday: "14-20",
         thursday:"14-20",
         friday:"14-20",
         saturday:"10-14",
         sunday:"Lukket"
      },
      id:"11"
   },
   {
      name:"Al-Diwan",
      review: 38,
      location:"koebenhavn",
      desc:"Traditional Moghul Cuisine.",
      info:"The great Mughuls were known for their art, style and cuisine.They built great monuments and palaces like Taj Mahal and Shalimar,world reknown for their everlasting beauty. In the same manner they left exotically great traditions of food.As a tribute to them and their sense of delicacies, we are proud to call our restaurant “AL-DIWAN” where we will do our best to relive andrevive their great cuisine.",
      locationref:"http://maps.apple.com/?daddr=Al-Diwan,+Vesterbrogade,+København&dirflg=d&t=h",
      image:"https://usercontent.one/wp/www.al-diwan.dk/wp-content/uploads/2021/12/248975435_4562372517190237_2493968354136850973_n-1024x576.jpeg",
      slug:"al-diwan",
      address:"Vesterbrogade 94, 1620 København",
      openinghours: {
         monday: "17-23",
         tuesday: "17-23",
         wednesday: "17-23",
         thursday:"17-23",
         friday:"17-23",
         saturday:"17-23",
         sunday:"17-23"
      },
      id: "12"
   },
   {
      name:"Australian Barbecue",
      review: 47,
      location:"aalborg",
      desc:"Du ved aldrig, hvornår du spiser godt igen",
      info:"Er dit sikre valg af mad, uanset om det er aftensmad som take away nu og her – eller ‘mad ud huset’ til din store fest.",
      locationref:"http://maps.apple.com/?daddr=Takeaway+Australian+Barbecue,+Østerbro,+Aalborg&dirflg=d&t=h",
      image:"https://australian.dk/File/113/family.jpg?width=590&stretchmode=UniformToMax&ticks=637562417250000000",
      slug:"australian-barbecue",
      address:"Østerbro 35, 9000 Aalborg",
      openinghours: {
         monday: "15-20:30",
         tuesday: "15-20:30",
         wednesday: "15-20:30",
         thursday:"15-20:30",
         friday:"15-20:30",
         saturday:"15-20:30",
         sunday:"15-20:30"
      },
      id: "13"
   },
   {
      name:"Ombord",
      review: 3,
      location:"aalborg",
      desc:"Et samlingssted i Aalborgs Vestby for alle byens livsnydere.",
      info:"Ombord er åben til frokost og til aften alle ugens syv dage, hvor der bliver serveret ærlig mad lavet fra bunden af gode kvalitetsråvarer og med fokus på hjemmelavede, velsmagende retter. Bag restauranten står Kristian Lauesen og Jesper Robert Jensen, der begge er uddannede tjenere og i mange år har drevet Café Luna og Pandekagehuset i Aalborg. De driver restauranten ud fra stærke principper om gæstfrihed, tilgængelighed, grundighed og åbenhed – alt sammen for at sikre kvalitet, service og ordentlighed.",
      locationref:"http://maps.apple.com/?daddr=Ombord+Aalborg,+Bådehavnsvej,+Aalborg&dirflg=d&t=h",
      image:"https://media-cdn.tripadvisor.com/media/photo-s/18/bb/00/8b/photo5jpg.jpg",
      slug:"ombord",
      address:"Bådehavnsvej 16A, 9000 Aalborg",
      openinghours: {
         monday: "11:30-22",
         tuesday: "11:30-22",
         wednesday: "11:30-22",
         thursday:"11:30-22",
         friday:"11:30-23",
         saturday:"11:30-23",
         sunday:"11:30-22"
      },
      id:"14"
   },
   {
      name:"I Pupi Siciliani",
      review: 8,
      location:"odense",
      desc:"Autentisk italiensk mad, med den bedste smag fra Sicilien",
      info:"Besøg vores Italienske Restaurant i Odense, I Pupi Siciliani med rødder i vores land, Sicilien og smag de mange retter fra det klassiske italienske køkken.",
      locationref:"http://maps.apple.com/?daddr=I+Pupi+Siciliani,+Vindegade,+Odense&dirflg=d&t=h",
      image:"https://www.ipupisiciliani.dk/wp-content/uploads/2019/06/hjemmeside-3.jpg",
      slug:"i-pupi-siciliana",
      address:"Vindegade 73, 5000 Odense",
      openinghours: {
         monday: "Lukket",
         tuesday: "Lukket",
         wednesday: "17:30-22",
         thursday:"17:30-22",
         friday:"17:30-22",
         saturday:"17:30-22",
         sunday:"17:30-22"
      },
      id: "15"
   },
]
